name: learn-github-actions
on: 
  push:
    branches:
      - main
jobs:
  check-bats-version:
    name: first job
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - run: pip install numpy && pip install pandas
      - run: bats -v
